version: "3"

services:
  postgres:
    container_name: quickstart-postgres
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  mongo:
    container_name: quickstart-mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongo:27017/

  